[data]
objects = ["ground", "glass_ball", "metal_ball", "cube"]

[world]
sky_colour = [1.0, 1.0, 1.0]

[ground]
type = "quad"
Q = [-50.0, -0.5, -50.0]
u = [100.0, 0.0, 0.0]
v = [0.0, 0.0, 100.0]
material = "mat_ground"

[glass_ball]
type = "sphere"
position = [1.2, 0.0, 0.0]
radius = 0.5
material = "mat_glass"

[cube]
type = "cube"
a = [-0.5, -0.5, -0.5]
b = [0.5, 0.5, 0.5]
material = "mat_diffuse"

[metal_ball]
type = "sphere"
position = [-1.2, 0.0, 0.0]
radius = 0.5
material = "mat_metal"

# -----------------
# Materials
# -----------------

[mat_ground]
type = "diffuse"
albedo = [0.2, 0.2, 0.25]

[mat_glass]
type = "glass"
ior = 1.33

[mat_metal]
type = "metal"
albedo = [0.8, 0.6, 0.2]
roughness = 0.0

[mat_diffuse]
type = "diffuse"
albedo = [0.7, 0.3, 0.3]
