[data]
objects = ["ground", "orange_ball", "ball", "blue_ball"]

[ground]
position = [0.0, -100.5, 0.0]
radius = 100.0
material = "diffuse"

[orange_ball]
position = [-1.0, 0.0, 0.0]
radius = 0.5
material = "orange"

[ball]
position = [0.0, 0.0, 0.0]
radius = 0.25
material = "diffuse"

[blue_ball]
position = [1.0, 0.0, 0.0]
radius = 0.5
material = "blue"

# -----------------
# Materials
# -----------------

[orange]
type = "emissive"
emission = [5.0, 1.0, 0.3]

[diffuse]
type = "diffuse"
albedo = [1.0, 1.0, 1.0]

[blue]
type = "emissive"
emission = [0.3, 1.0, 5.0]
